### ISSUE TITLE
How to install Node.js and NVM on a PC computer

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#1]
We need an article with clear instructions on how to install NVM and Node.js on a PC computer.

The article has to be written in markdown language following [these guidelines](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md).

**Comment by kodi24fever** [comment]
Is that PC running on Windows, Mac, or Linux? Because I can do a guide for Windows environments.

**Comment by alesanchezr** [comment]
Hey Frank, its just for windows because mac and linux already have it.

**Comment by kodi24fever** [comment]
Awesome I will do it!!

**Comment by alesanchezr** [comment]
@all-contributors please add kodi24fever for documentation
