### ISSUE TITLE
Artícle Title: Javascript Empty Array

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1447]
Keywords & Synonyms:
javascript empty array
javascript check if array is empty
check if array is empty javascript
empty array javascript

Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by DF27ARTS** [comment]
PR link : https://github.com/breatheco-de/content/pull/1426

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
