### ISSUE TITLE
Artícle Title: Expresiones Regulares Python

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1448]
## Estructura del Articulo:

- Introduccion a las expresiones regulares en python
- Ejemplos de expresiones regulares en python
- Metodos de expresiones regulares en python
- Casos de Uso
- Conclusion breve

## Keywords & Sinonimos:

expresiones regulares python
python expresiones regulares
expresiones regulares en python
python expresiones regulares ejemplos
expresiones regulares python ejemplos
expresiones regulares python 3
expresiones regulares con python

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by danielmoret** [comment]
https://github.com/breatheco-de/content/pull/1475

**Comment by tommygonzaleza** [comment]
Te agregue un review en el PR, el resto del articulo esta perfecto, asi es como queremos que queden todos

**Comment by danielmoret** [comment]
Cambios realizados https://github.com/breatheco-de/content/pull/1475

**Comment by tommygonzaleza** [comment]
Te pedi cambios en el PR, referente al ejemplo de codigo y la introduccion

**Comment by danielmoret** [comment]
Cambios realizados https://github.com/breatheco-de/content/pull/1475

**Comment by danielmoret** [comment]
Nuevos cambios https://github.com/breatheco-de/content/pull/1475

**Comment by tommygonzaleza** [comment]
El articulo no puede ser realizado con AI, por favor haz cambios para que este hecho por ti
<img width="355" alt="Screenshot 2023-05-25 at 11 16 43 AM" src="https://github.com/breatheco-
de/content/assets/56565994/c0079685-d8c0-4ca4-b603-d04161f718f5">

**Comment by danielmoret** [comment]
https://github.com/breatheco-de/content/pull/1520

**Comment by tommygonzaleza** [comment]
Te pedi un cambio en el PR, es sobre el primer ejemplo, de resto esta perfecto. Igual chequea los cambios hice en [este commit](https://github.com/breatheco-de/content/pull/1520/commits/0dc646da98149a4774816b06a7f88b6c5c83329d), para que en los proximos no haga falta recordarlo o cambiarlo:

**Comment by danielmoret** [comment]
https://github.com/breatheco-de/content/pull/1520

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
