### ISSUE TITLE
Artícle Title: Expresiones Regulares Ejemplos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1449]
## Article Structure:

- Introduccion a los ejemplos de Expresiones Regulares
- 3 Ejemplos de expresiones regulares con Javascript
- 3 Ejemplos de expresiones regulares con Python (Los mismos ejemplos)
- Breve conclusion de estos ejemplos

## Keywords & Synonims:

- expresiones regulares ejemplos
- ejemplos expresiones regulares
- ejemplos de expresiones regulares
- expresiones regulares ejemplos resueltos

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

> Yamil

**Comment by tommygonzaleza** [comment]
https://github.com/breatheco-de/content/pull/1469

**Comment by tommygonzaleza** [comment]
Hay que hacer varios cambios al articulo, no se muestran casi ejemplos, lo ideal seria que el articulo tenga 3 ejemplos de expresiones regulares con Javascript y los mismos 3 ejemplos de expresiones pero con python. Los ejemplos serian ejemplos de uso, no los diferentes tipos de expresiones regulares

**Comment by YamilMS** [comment]
Perdón por la tardanza. Ya está modificado. Mucho curro la semana pasada.
En principio el articulo tiene 6 ejemplos en JS y 6 en Python. Cree un
nuevo pull request y cerré el anterior, lo siento.

**Comment by tommygonzaleza** [comment]
Los ejemplos que agregaste son muy basicos, agrega estos ejemplos para cada uno de los lenguajes:
- Que un email tenga la estructura correcta
- Encontrar un link en un texto
- Utilizando el flag de `i` para un ejemplo de un caso no case sensitive

**Comment by DF27ARTS** [comment]
(Expresiones Regulares Ejemplos) ready for review, pull request: https://github.com/breatheco-de/content/pull/1783

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
