### ISSUE TITLE
Artícle Title: Expresiones Regulares Linux

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1450]
## Keywords & Synonims:

expresiones regulares linux
expresiones regulares en linux
linux expresiones regulares
expresiones regulares linux ejemplos

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by Gilberto-MV** [comment]
PR Link: [https://github.com/breatheco-de/content/pull/1445](url)

**Comment by tommygonzaleza** [comment]
Se pidieron cambios en el PR

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
