### ISSUE TITLE
Artícle Title: PHP Expresiones Regulares

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1451]
## Keywords & Synonims:

php expresiones regulares
expresiones regulares php ejemplos
expresiones regulares en php
expresiones regulares php

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

> Diego Rojas

**Comment by tommygonzaleza** [comment]
- [ ] Recuerda agregar una breve introduccion al ejemplo y una explicacion breve tambien justo despues del ejemplo
- [ ] Empieza con la pregunta Que son las expresiones regulares en PHP pero la respuesta no dice que son sino para que son. Puedes poner `"las expresiones regulares en PHP son ... y ellas nos permiten ..."`
- [ ] Poner como subtitulo cada uno de los ejemplos de los metodos y agregar la breve explicacion del ejemplo

**Comment by DF27ARTS** [comment]
Pull request link: https://github.com/breatheco-de/content/pull/1464

**Comment by DF27ARTS** [comment]
expresiones regulares php updated, PR link https://github.com/breatheco-de/content/pull/1468

**Comment by tommygonzaleza** [comment]
Agregue un comentario en el PR
