### ISSUE TITLE
Artícle Title: Javascript Array Some

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1452]
## Keywords & Synonyms:

javascript array some
array some javascript
some array javascript
array some method in javascript

> Language: English

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by Bran18** [comment]
PR Link: https://github.com/breatheco-de/content/pull/1443

**Comment by tommygonzaleza** [comment]
Revisa los cambios que hice en este [commit](https://github.com/breatheco-de/content/pull/1443/commits/c746406cb3adeef11e56ed06a34251f9c0850827) para que los corrijas en el proximo articulo

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
