### ISSUE TITLE
Artícle Title: Javascript Array Intersection

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1453]
## Keywords & Synonims:

javascript array intersection
array intersection javascript
javascript array intersection numbers
javascript get intersection of array

> Language: English

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by jul1998** [comment]
https://github.com/breatheco-de/content/pull/1465

**Comment by tommygonzaleza** [comment]
Revisa los cambios que tuve que hacer en [este commit](https://github.com/breatheco-de/content/pull/1465/commits/07e4c48598e189d2926d11de24dafcd1194a3f9b), para que no vuelvan a pasar en futuros articulos

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
