### ISSUE TITLE
Artícle Title: Recorrer Array Javascript

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1455]
## Article Structure:

- Introduccion breve con un ejemplo de como recorrer un array con un for loop
- Diferentes formas de recorrer un array con un for loop, for in, for of, while, map, forEach (Un ejemplo de cada uno).
- Casos de uso (Dos ejemplos)
- Conclusion

## Keywords & Synonims:

- recorrer array javascript
- recorrer un array javascript
- recorrer array de objetos javascript
- javascript recorrer array
- javascript recorrer array de objetos

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by Gilberto-MV** [comment]
PR Link: [https://github.com/breatheco-de/content/pull/1503]

**Comment by tommygonzaleza** [comment]
Te agrege cambios en el PR

**Comment by Gilberto-MV** [comment]
Cambios del PR aplicados

**Comment by tommygonzaleza** [comment]
Te pedi cambios de nuevo con un nuevo review en tu PR

**Comment by Gilberto-MV** [comment]
Cambios realizados

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
