### ISSUE TITLE
Artícle Title: Clone Array Javascript

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1459]
## Keywords & Synonyms:

- javascript clone array
- clone array javascript
- javascript array clone
- clone an array javascript
- array clone javascript

> Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by valerybriz** [comment]
This issue is solved by the PR #1437

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
