### ISSUE TITLE
Strings en Javascript - ES

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1476]
## Article Structure

- Ejemplo de un string en javascript (Con una breve introduccion antes).
- Que es un string en javascript
- Para que sirven los strings en Javascript
- Como declarar un string en Javascript
- Ejemplos de Uso

## Language

Spanish

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Javascript String o cadenas de caracteres>` (preapproved cluster).
- URL to topic cluster landing page: `<Add here>`.

## Recommended Keywords or synonyms

- comparar strings en javascript 
- concatenar strings en javascript

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster. (https://4geeks.com/es/lesson/que-es-javascript-aprende-a-programar-en-javascript)
- [ ] Think hard: What other articles are related and are worth mentioning? 

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

## point the PR to this URL: https://github.com/breatheco-de/content/blob/master/src/content/lesson/strings-en-javascript.es.md
[comparar strings en javascript](https://app.ahrefs.com/keywords-explorer/google/es/overview?keyword=comparar%20strings%20en%20javascript)
N/A
0–10	20	N/A	
N/A
N/A
N/A
N/A
N/A

[concatenar strings en javascript](https://app.ahrefs.com/keywords-explorer/google/es/overview?keyword=concatenar%20strings%20en%20javascript)

**Comment by jul1998** [comment]
https://github.com/breatheco-de/content/pull/1514

**Comment by tommygonzaleza** [comment]
Te agregue un review en el PR. Por favor tambien revisa los cambios que hice en este [commit](https://github.com/breatheco-de/content/pull/1514/commits/0a6c7494ebb550df9078b503ee75b83b6d24161e) para que no se vuelvan a cometer

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
