### ISSUE TITLE
Reduce en Javascript - ES

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1481]
## Article Structure:

- Breve intro a un ejemplo y al articulo
- Ejemplo de codigo
- Explicacion de lo que hace el metodo reduce
- Parametros del metodo reduce
- Ejemplos del metodo reduce de sus diferentes variaciones
- Conclusion

## Language

Spanish

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Javascript Array>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/es/lesson/array-arreglo-en-javascript>`.

## Recommended Keywords or synonyms

- reduce en javascript
- como funciona reduce en javascript

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster. (https://4geeks.com/es/lesson/que-es-javascript-aprende-a-programar-en-javascript)
- [ ] Think hard: What other articles are related and are worth mentioning? 

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

**Comment by DF27ARTS** [comment]
Artículo reduce en javascript ready for review, link PR https://github.com/breatheco-de/content/pull/1510

**Comment by tommygonzaleza** [comment]
Te agregue un review en el PR

**Comment by tommygonzaleza** [comment]
Deje abiertos y con nuevos comentarios los review que hacen falta cambiar

**Comment by DF27ARTS** [comment]
Hice los cambios y agrege un comentario en la review.

**Comment by tommygonzaleza** [comment]
Revisa este [commit](https://github.com/breatheco-de/content/pull/1510/commits/6771de8da8e9f1ff18203d791f656128c246245e) para que veas los cambios que agregue y lo hagas de esa manera en el proximo articulo

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by DF27ARTS** [comment]
Dale perfecto gracias, lo tendre en cuanta para el proximo.
