### ISSUE TITLE
Javascript Array Fill - EN

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1485]
## Article Structure

- A quick introduction to an example of the "fill" method. Then an example of the "fill" method and an explanation of the example.
- Explain what this method is used for and how to use it.
- Parameters that it receives
- Examples.
- Conclusion

## Language

English

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Javascript Array>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/lesson/what-is-an-array-define-array>`.

## Recommended Keywords or synonyms

- array fill javascript
- javascript array fill
- javascript fill array
- fill array javascript
- javascript fill array with same value
- javascript fill array with range
- new array fill javascript

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster. (https://4geeks.com/lesson/what-is-javascript-learn-to-code-in-javascript)
- [ ] Think hard: What other articles are related and are worth mentioning? 

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

## Point the PR to this URL: https://github.com/breatheco-de/content/blob/master/src/content/lesson/javascript-array-fill.us.md

**Comment by DF27ARTS** [comment]
JS fill method ready for review, PR link: https://github.com/breatheco-de/content/pull/1594

**Comment by DF27ARTS** [comment]
cambios realizados, PR https://github.com/breatheco-de/content/pull/1594/files.

Hice algnos comentarios de las soluciones que hice en el PR

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
