### ISSUE TITLE
expresiones regulares java ES

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1511]
## Article Structure:

- Introduccion a las expresiones regulares en java
- Ejemplos de expresiones regulares en java
- Metodos de expresiones regulares en java
- Casos de Uso
- Conclusion breve

## Language:

Spanish

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<expresiones regulares>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/es/lesson/regex-tutorial-regular-expression-ejemplo>`.

## Recommended Keywords or synonyms

probar expresiones  regulares java online
ejercicios expresiones regulares java
java expresiones regulares ejemplos
expresiones regulares java
tabla expresiones regulares java
comprobar expresiones regulares java

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

!Important:   Make sure of doing the Pull Request to the following file:  https://github.com/breatheco-de/content/blob/master/src/content/lesson/expresiones-regulares-java.es.md

**Comment by valerybriz** [comment]
PR: #1525

**Comment by tommygonzaleza** [comment]
Podrias agregarle una seccion como [esta](https://github.com/breatheco-de/content/blob/master/src/content/how-to/expresiones-regulares-python.md#metacaracteres-en-expresiones-regulares) de los metacaracteres mas importantes.

**Comment by valerybriz** [comment]
Claro, se lo agrego 👌

**Comment by tommygonzaleza** [comment]
Chequea estos metacaracteres, creo que son los que mas me interesaria leer, es como lo mas basico: https://desktop.arcgis.com/es/arcmap/latest/extensions/data-reviewer/metacharacters-used-to-build-regular-expressions.htm

Ve a Descripciones de Metacaracteres

**Comment by valerybriz** [comment]
Vale, los voy agregando

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
