### ISSUE TITLE
Instalar Pandas Python

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1534]
## Article Structure:

- Introduction to the article and the example of how to install pandas. Show quickly with a code example, how to install pandas on the terminal with pip.
- Explain how to install pandas on Windows, MacOS, and Ubuntu.
- What is pandas in python? Reference the `panda-python` article.
- How to update pandas version?
- Conclusion

## Language:

Spanish

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Tutorial de Python Pandas>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/es/interactive-exercise/tutorial-pandas-para-machine-learning>`.

## Recommended Keywords or synonyms

instalar pandas en python
instalar pandas en python windows
instalar modulo pandas python
instalar pandas en python 3
instalar libreria pandas en python

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

Send Pull Request to this article: https://admin.4geeks.com/media/asset/instalar-pandas-python

**Comment by DF27ARTS** [comment]
Instalar Pandas en Python ready for review, link PR: https://github.com/breatheco-de/content/pull/1568

**Comment by tommygonzaleza** [comment]
Revisa los cambios que hice en este [commit](https://github.com/breatheco-de/content/pull/1568/commits/1ed58a838d2fe01c1632d07fb9e17b5d5be0d09b) para que los hagas en los proximos articulos

**Comment by DF27ARTS** [comment]
Dale perfecto, los voy a revisar

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
