### ISSUE TITLE
Regex Letter - ENG

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1597]
## Article Structure:

- Two lines introduction to a code example and the article. then a quick code example and an explanation of what is done in the example
- How to look for letters in regex?
- Examples (Contains letters, Starts with a letter, finishes with a letter, it has at least one uppercase and one lowercase letter)
- Conclusion

## Language:

English

## Meta Info

- Number of words: recomendations: ~800 words for standard articles, 1500+ for topic cluster articles
- URL to topic cluster landing page: `https://4geeks.com/lesson/regex-tutorial-regular-expression-examples`.

## Recommended Keywords or synonyms

regex letter 
regex capitalize first letter 
regex any letter 
regex start with a letter 
regex digit or letter

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

Make sure of pointing PR to:  https://github.com/breatheco-de/content/blob/master/src/content/how-to/regex-letter.us.md

**Comment by DF27ARTS** [comment]
Article Regex letters created, PR link:https://github.com/breatheco-de/content/pull/1622

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
