### ISSUE TITLE
Pandas Data Cleaning EN

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1601]
## Article Structure:

- Introduccion al articulo.
- Explicacion que se debe hacer para limpiar un dataset en python brevemente
- Detallar cada uno de los pasos como un tutorial, explicando como limpiar el dataset
- Conclusion

## Language:

English

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Pandas Tutorial and Exercises>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/interactive-exercise/pandas-exercises-tutorial>`.

## Recommended Keywords or synonyms

pandas data cleaning
data cleaning pandas
pandas cleaning data
pandas data cleaning cheat sheet
cleaning data with pandas
python pandas data cleaning

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

Please send the PR to the following URL: https://github.com/breatheco-de/content/blob/master/src/content/how-to/pandas-data-cleaning.us.md

**Comment by DF27ARTS** [comment]
Pandas data cleaning ready for review, link PR: https://github.com/breatheco-de/content/pull/1603

**Comment by tommygonzaleza** [comment]
Te pedi unos cambios en tu PR, solo falta cambiar un ejemplo que no estoy seguro de si funciona como esta

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
