### ISSUE TITLE
React Global Context - EN

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1642]
## Article Structure:

- Quick introduction for dummies about the global context in react, a quick code example of how to apply it.
- What does Global Context mean in React?
- How to apply global context in a React project? Explain step-by-step with a code example of a real case simple project.
- benefits and drawbacks of using Global Context
- Conclusion

## Language:

English

## Meta Info

- Number of words: `<Add here>` (recommendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<React JS Tutorial Exercises>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/interactive-exercise/react-js-tutorial-exercises>`.

## Recommended Keywords or synonyms

react global context
react native global context
use global context react
react global state context

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

Send the PR to this URL: https://github.com/breatheco-de/content/blob/master/src/content/lesson/react-global-context.us.md

**Comment by DF27ARTS** [comment]
React Global Context ready for review, Pull request: https://github.com/breatheco-de/content/pull/1657

**Comment by DF27ARTS** [comment]
Cambios en el articulo realizados, nuevo projecto de ejemplo y esplicaciones mejoradas.

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
