### ISSUE TITLE
¿Cómo instalar Python?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1647]
Crear lesson de como instalar Python Local, debe ser similar a lo que explica en este: https://algoritmosyprogramacionunimet.notion.site/0-Getting-you-started-6fcccdb959ec42a7b0be15d84bd75181 Tomalo como guia pero hazlo mas interactivo.

- Explica como hacerlo en Mac, Linux y Windows. Paso a paso, agrega videos tutoriales y valida que esten funcionando (Haz tu el paso a paso para instalarlo)

**Comment by DF27ARTS** [comment]
¿Cómo instalar Python? ready for review, Pull request https://github.com/breatheco-de/content/pull/1653.

**Comment by tommygonzaleza** [comment]
- [ ] Las imagenes tienen baja resolucion

**Comment by DF27ARTS** [comment]
Ya cambie los videos por el code <iframe/> de youtube.

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
