### ISSUE TITLE
¿Cómo crear un diagrama de clases UML?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1696]
- [ ] Explicar paso a paso como crear un diagrama de clases UML
- [ ] Nombrar las aplicaciones mas comunes (Tu en este caso utilizar la que consideres la mejor)
- [ ] Conclusion hablando de los beneficios de un diagrama de clases UML

**Comment by DF27ARTS** [comment]
¿Cómo crear diagramas de clases UML? ready for review, pull request: https://github.com/breatheco-de/content/pull/1716

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
