### ISSUE TITLE
¿Qué son las librerías de terceros y cómo usarlas?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1698]
- [ ] Agregar una breve introduccion y un breve ejemplo de como importar y usar una libreria de un tercero
- [ ] Breve explicacion de que son las librerias de terceros, como descargarlas, importarlas y usarlas en tu codigo. Menciona tambien para que sirven
- [ ] Incluir ejemplos de como usar librerias de terceros, deben ser descargadas estas librerias de terceros (No sirven los modulos que incluye python como datetime o random).
- [ ] Conclusion que tome en cuenta los beneficios de utilizarlas

**Comment by DF27ARTS** [comment]
Cambios realizados

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
