### ISSUE TITLE
What does double equal sign mean in Python?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1702]
- [ ] Add a quick intro to the article and example, and an example about a use of doble equal sign in python.
- [ ] Add a quick explanation of the example
- [ ] Explain what does the double equal sign mean
- [ ] Add examples of using it in conditions, add three examples and explain them.
- [ ] Conclusion

**Comment by jul1998** [comment]
https://github.com/breatheco-de/content/pull/1715

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
