### ISSUE TITLE
Pandas drop - ES

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/content#1712]
## Article Structure:

1. Introduccion a un ejemplo de codigo y al articulo. Un breve ejemplo de como usar el metodo drop() en Pandas y una explicacion de lo que se hizo en el ejemplo.

2. Conceptos Básicos de la Función drop():

- Explicación detallada del método drop() en Pandas.
- Uso de los parámetros clave: labels, axis, index, columns, inplace, etc.

3. Identificación de Columnas a Eliminar:

- Cómo identificar columnas irrelevantes o redundantes en un DataFrame.
- Importancia de la comprensión del conjunto de datos antes de eliminar columnas.

4. Eliminación de Columnas: Paso a Paso:

- Ejemplo 1: Eliminación de una sola columna por nombre.
- Ejemplo 2: Eliminación de múltiples columnas utilizando una lista.
- Ejemplo 3: Eliminación de columnas basadas en una condición.

5. Uso de la Opción inplace:

- Explicación del parámetro inplace y cómo afecta a los DataFrames.
- Ventajas y desventajas de utilizar inplace en la eliminación de columnas.

6. Conclusiones y Pasos Adicionales:

- Recapitulación de los conceptos aprendidos sobre la eliminación de columnas con Pandas.
- Animo a los lectores a practicar y explorar casos más complejos.
- Invitación a continuar aprendiendo sobre otras funciones y capacidades de Pandas.

## Language:

Spanish

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- Topic Cluster: `<Tutorial de Python Pandas>` (preapproved cluster).
- URL to topic cluster landing page: `<https://4geeks.com/es/interactive-exercise/tutorial-pandas-para-machine-learning>`.

## Recommended Keywords or synonyms

drop duplicates pandas
drop pandas
pandas drop index
pandas drop rows

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Include keyword in the first 100 words.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the PR of the article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure you read the [writers welcome tutorial](https://4geeksacademy.notion.site/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f) with the writing recommendations

Make sure point the PR to the following URL:  https://github.com/breatheco-de/content/blob/master/src/content/lesson/pandas-drop.es.md

**Comment by DF27ARTS** [comment]
[metodo drop pandas] ready for review, pull request: https://github.com/breatheco-de/content/pull/1880

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
