### ISSUE TITLE
¿Cómo consumir un API en python?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1732]
- Agrega una breve introduccion al articulo y a un ejemplo que demuestre como consumir un API en python (Con la libreria de requests)
- Explica brevemente que son los APIs en python
- Agrega un ejemplo de un GET, otro de un POST, otro de un PUT, y otro de un DELETE.
- Conclusion

**Comment by DF27ARTS** [comment]
¿Cómo consumir una API en python? ready for review, pull request: https://github.com/breatheco-de/content/pull/1740
