### ISSUE TITLE
¿Cómo leer un archivo en Python?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1733]
Queremos mejorar la explicacion que estan haciendo en este articulo: https://algoritmosyprogramacionunimet.notion.site/1-Lectura-de-Archivos-e591154f9d314a3d97c0359ddcd604b6

Basicamente estamos creando este articulo para que puedan entender mejor lo que aparece en el que te puse antes. Explica las funciones y pon ejemplos de codigo igual.

## Estructura del Articulo

- Inicia con una breve introduccion al articulo y a un ejemplo donde muestres como leer un archivo. Luego del ejemplo explica lo que se hizo
- ¿Cómo leer el contenido de un archivo?
- ¿Cómo modificar el contenido de un archivo?
- Utilización de un archivo txt para almacenar datos. Agrega como subpuntos la explicacion de como agregar una lista de diccionarios en el txt. Como leer el txt y convertir el contenido de nuevo en una lista de diccionarios.
- Conclusion

**Comment by DF27ARTS** [comment]
¿Cómo leer un archivo en python? ready for review, pull requst: https://github.com/breatheco-de/content/pull/1747

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
