### ISSUE TITLE
Algoritmos de Ordenamiento y Búsqueda en Python 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1735]
# Algoritmos de Ordenamiento y Búsqueda en Python 📊🔍

- Breve introducción de por qué son importantes los algoritmos de ordenamiento y búsqueda.
- ¿Qué son los Algoritmos de Ordenamiento? 📊🔄
- ¿Cúales son los algoritmos de ordenamiento más conocidos? (Ordenamiento de Burbuja o bubble sort, Ordenamiento por Inserción) Agregales ejemplo de codigo
- ¿Qué son los Algoritmos de Búsqueda?
- ¿Cúales son los algoritmos de búsqueda más conocidos? (Búsqueda Lineal,  Búsqueda Binaria) Agregales ejemplo de codigo
- Ventajas y Desventajas de los Algoritmos explicados antes 🌟📉
- Conclusion

**Comment by DF27ARTS** [comment]
Algoritmos de ordenamiento y búsqueda en Python, ready for review, pull requests: https://github.com/breatheco-de/content/pull/1743
