### ISSUE TITLE
lessson git version control

### ISSUE THREAD

**Issue by Camilocoo** [breatheco-de/content#19]
agregar parrafo entre imagenes ![git0](https://ucarecdn.com/0ef9f84a-33b8-4312-a4ba-a6a83187f865/)
[git1](https://ucarecdn.com/da752daa-7d21-4044-bf7b-bf686934b2a8/)

**Comment by alesanchezr** [comment]
vamos a esperar a que se corrigan las imagenes para ver que carrizo era este issue.
