### ISSUE TITLE
¿Cómo instalar Pyenv en Mac?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1912]
## Article Structure:

- Explicar paso a paso de como instalar Pyenv.
- Hacer referencia al articulo de que es pyenv y como instalar pyenv en un breve parrafo
- Conclusion

## Language:

Spanish

## Pull Request:

Create the pull request of the article on this file:

```
https://github.com/breatheco-de/content/blob/master/src/content/how-to/instalar-pyenv-mac.md
```

**Comment by DF27ARTS** [comment]
[¿Cómo instalar Pyenv en Mac?] ready for review, pull request: https://github.com/breatheco-de/content/pull/1926

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
