### ISSUE TITLE
Pandas Dataframe Tutorial

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#1913]
## Article Structure:

- Introduccion al articulo (El articulo es un tutorial desde cero sobre como utilizar un dataframe de pandas, se profundiza desde lo mas basico hasta los diferentes metodos que tiene)
- Explicar que es un dataframe (Agregar link de articulo de que es un dataframe)
- Como crear un dataframe de pandas
- Metodos mas importantes para operaciones basicas de un dataframe (Filtrar, ordenar, calcular cosas con los datos)
- Metodos mas importantes para la limpieza de los datos de un dataframe
- 3 casos de uso de un dataframe
- Conclusion

## Language:

Spanish

## Pull Request:

```
https://github.com/breatheco-de/content/blob/master/src/content/lesson/pandas-dataframe-tutorial.es.md
```

**Comment by DF27ARTS** [comment]
[Pandas Dataframe Tutorial] ready for review, pull request: https://github.com/breatheco-de/content/pull/1954

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
