### ISSUE TITLE
Clone Array JavaScript

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#2008]
## Article Structure:

- Quick one-line intro to the article, and a code example of how to clone an array in JavaScript, with an explanation of what you did on the example.
- Explain what cloning an array means in JavaScript.
- Different ways of cloning an array.
- Different case scenarios of when you should clone an array in JavaScript 

## Language:

English

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- URL to topic cluster landing page: https://4geeks.com/lesson/what-is-an-array-define-array

**Comment by DF27ARTS** [comment]
[Clone Array Javascript] ready for review, pull request: https://github.com/breatheco-de/content/pull/2010
