### ISSUE TITLE
¿Qué se puede hacer con Python?

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#2009]
## Article Structure:

- Breve introduccion al articulo, explicando un poco lo versatil que es python.
- Campos en los que puedes que se utiliza python (Data Science, Back-End development, etc). En este punto debes profundizar en cada uno de los campos, habla de los frameworks mas importantes.
- Conclusion de nuevo habla sobre la versatilidad de python y la cantidad de posibilidades que tienes al usarlo. Agrega tambien una referencia al curso de python de 4geeks.com con un link

## Language:

Español

## Meta Info

- Number of words: `<Add here>` (recomendations: ~800 words for standard articles, 1500+ for topic cluster articles).
- URL to topic cluster landing page: https://4geeks.com/es/lesson/que-es-python-tutorial.

**Comment by DF27ARTS** [comment]
[¿Qué se puede hacer con Python?] ready for review, pull request: https://github.com/breatheco-de/content/pull/2020

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
