### ISSUE TITLE
Regex for end of line (EN)

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#2067]
- [ ] Quick intro and example of a regex that checks for end-of-line in javascript.
- [ ] Explain the regex to check for end of line and each of the characters used in the regex (On both Javascript and Python).
- [ ] 3 Case scenarios where you can use a regex that checks for end of line (With the regex for each example) with JS and python
- [ ] Conclusion

**Comment by DF27ARTS** [comment]
[Regex for end of line] ready for review, pull request: https://github.com/breatheco-de/content/pull/2070

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by DF27ARTS** [comment]
[Regex for end of line] updated, pull request: https://github.com/breatheco-de/content/pull/2070
