### ISSUE TITLE
Regular Expression Examples

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/content#2104]
- Breve introduccion al articulo y a un ejemplo de expresion regular con Javascript y Python. Luego una explicacion de lo que se hizo en el ejemplo. Asi es como debes hacer para que se muestren ambos ejemplos:
![Screenshot 2024-01-31 at 7 37 19 AM](https://github.com/breatheco-de/content/assets/56565994/f4060bf3-37cd-482d-b533-3ddf95c9144b)
- Agrega 5 ejemplos de expresiones regulares, cada ejemplo lo agregas en javascript y python con el formato que te puse en la imagen anterior.
- Conclusion

**Comment by DF27ARTS** [comment]
[Regular Expression Examples] ready for review, pull request: https://github.com/breatheco-de/content/pull/2146

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
