### ISSUE TITLE
DAY 20 - "Todo lo que necesitas saber sobre SQLAlchemy": Error en el ejemplo de "Porqué usarlo?" y en el montaje de la sección "Definiendo nuestro Models/Tables"

### ISSUE THREAD

**Issue by alexcastillla** [breatheco-de/content#332]
Cuando se explica en que consiste el ORM, se muestra un ejemplo en la versión inglesa en donde se comenta que para realizar la traducción a SQL de nuestro código, hay que realizar un **db.session.commit()** , en cambio en la versión en castellano aparece un **user.save()**, por lo que genera un error en su comprensión.

Versión en Inglés:
`You can just say: db.session.commit() and all the things you have done in your code will be translated into SQL language code.`

Versión que aparece en Español:
`Solo puede decir: user.save () y el ORM lo traducirá a SQL.`

Versión sugerida en Español:
`Con escribir la linea de código db.session.commit(), aseguraremos de que los cambios realizados en la base de datos son coherente y de que todo el código escrito anteriormente será traducido a lenguaje SQL mediante el ORM.`

Por último, comentar que en la sección de **Definiendo nuestro Models/Tables** aparece en el código de ejemplo de python lo siguiente:

![Captura](https://user-images.githubusercontent.com/70212775/98446521-424cd880-211e-11eb-93d2-658ef31f0d4e.JPG)

Como se puede ver, se ha añadido la traducción correspondiente a la sección dentro de la caja de código, y a su vez, se ha duplicado el user.save() de la sección anterior y del cual he hablado anteriormente.

**Comment by alesanchezr** [comment]
Gracias!!
