### ISSUE TITLE
Prework's first day has several issues in Learn HTML lesson

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/content#345]
Al redactar el contenido se omitieron o escribieron mal los ejemplos de etiquetas y al leer el contenido como estudiante, se ven las etiquetas mal escritas o incompletas: sin abrir, sin cerrar, sin completar...

![image(2)](https://user-images.githubusercontent.com/410890/100012629-de8c0600-2dd3-11eb-9a40-36f0d1654e0a.png)
![image(1)](https://user-images.githubusercontent.com/410890/100012632-df249c80-2dd3-11eb-84ad-e25ceefbe53b.png)

**Comment by ElviraQDP** [comment]
marco ¿me puedes decir que lección es?
