### ISSUE TITLE
Include Base URL in Contact API documentation

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/content#380]
When a student is reading the API documentation at https://assets.breatheco.de/apis/fake/contact/, sometimes doesn't realize that the base url is the same in the browser URL. This has happened several times, students ask for help because they are doing requests to `/api/....` because the documentation does not specify that the domain is assets.breatheco.de

**Comment by ElviraQDP** [comment]
are you planning on doing the enhancement @marcogonzalo ?
