### ISSUE TITLE
It's Time To Learn What is an Array_Removing Elements (pop function)

### ISSUE THREAD

**Issue by TheHotelCoder** [breatheco-de/content#402]
The description of the method states: 
_Removing an element has the exact same limitations as in adding an element: you can only remove an element from the last position using the **pull() function._**

It should say:
_Removing an element has the exact same limitations as in adding an element: you can only remove an element from the last position using the **pop**() function.(method?)
![pop()](https://user-images.githubusercontent.com/74969634/108723276-5af1ca80-7524-11eb-90cb-474c099fbc9f.JPG)

**Comment by alesanchezr** [comment]
@ElviraQDP what can you fix this?

**Comment by ElviraQDP** [comment]
comment added
