### ISSUE TITLE
Youtube video from link is private

### ISSUE THREAD

**Issue by vitortamberlini** [breatheco-de/content#579]
The link over this part of the article:

> Click here to access a video that explains how a Google Chrome Book works.

Goes to a video that is currently private.

**Comment by tommygonzaleza** [comment]
Can you tell us what video you are referring to please

**Comment by vitortamberlini** [comment]
Oh, so when I open an issue, it doesn't point exactly to the article that I was reading?
If so, my bad! Now I don't remember where exctly I was... 🤔

I apologize for that, and I'll keep that in mind for the next issues that I open! 😄
