### ISSUE TITLE
Propuesta de UI/UX para el home the breatheco.de

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#59]

**Comment by alesanchezr** [comment]
Epa no cierres tu esto. Porque no la hemos procesado.

**Comment by alesanchezr** [comment]
Solo podriamos cerrarla si ya breatheco.de tuviera tu pagina montada.

**Comment by Camilocoo** [comment]
@alesanchezr a listo dale esque pense que ya habiamos acabado eso y ya estvamos en la siguient fase que era lo del desarrollo

**Comment by alesanchezr** [comment]
A pues si, pero quedo como a medias, nunca tuvimos un wireframe ni nada. Si quieres busca a ver si hay un issue para la parte de desarrollo, si no hay lo creas... y asi podemos cerrar este.

**Comment by Camilocoo** [comment]
Listo cree este issue para continuar https://github.com/breatheco-de/content/issues/80
