### ISSUE TITLE
Fix layout for `how-to` and `error` articles.

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#61]
The layout for the `lesson` is ready, but the other two layouts are not ready, they need to look the same.

**Comment by RafaelEsaa** [comment]
Se modifico el template para que pueda estar igual con respecto al resto y se cambio el nombre de blog-post a default.

**Comment by alesanchezr** [comment]
Pero el layout the lesson era lesson.js creo. Miestrame una foto de como quedo.

**Comment by alesanchezr** [comment]
a que branch publicaste esto?
