### ISSUE TITLE
Add google analytics to content.breatheco.de

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#62]
Container id: `GTM-574Z6C5`

https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/

**Comment by RafaelEsaa** [comment]
Se agrego el plugin a gatsby.config, falta agregar los id a "google tag manager id", "google tag manager auth string" y "google tag manager enviroment"

**Comment by alesanchezr** [comment]
Esos no y que son opcionales? yo no me se eso. Que debemos poner alli?

**Comment by alesanchezr** [comment]
Ya probaste que funciona? viste el script del tag manager? Hay un plugin de chrome q te dice si el tag maager se instalo exitosamente.

**Comment by RafaelEsaa** [comment]
Funciona! 
En las opciones del plugin en gatsby-config.js, linea 121 hay que modificar a true o false segun el ambiente donde se este ejecutando para que pueda funcionar.
includeInDevelopment: true (development)
includeInDevelopment: false (production)

**Comment by alesanchezr** [comment]
@RafaelEsaa eso no puede hacerse asi porque ese archivo esta dentro del repositorio. 

Ese valor `true` o `false` tiene que venir de un archivo que sea ignorado por git porque sino como voy a lograr que tenga differentes valores en produccion de pruebas? Tienes que usar environment variables, aqui esta la documentacion:

https://www.gatsbyjs.org/docs/environment-variables/

Configura eso, no hay ningun .env ahora mismo. avisame.

**Comment by alesanchezr** [comment]
@RafaelEsaa que ha pasado con esto?
