### ISSUE TITLE
Typo and ¿why legacy?

### ISSUE THREAD

**Issue by Gfervic** [breatheco-de/content#710]
❌  Actions can by triggered components (

✅  Actions can be triggered by components 

I strongly believe we should update all code examples to use functional components and hooks instead of saying

☝ This is a class component. We strongly recommend you to use functional components and hooks instead because class components are legacy.

It makes the process of learning react more confusing seeing legacy code. Either compare the 2 versions or just teach functional and hooks

**Comment by alesanchezr** [comment]
A couple of years have passed, I do believe we can stop showing the legacy version today.

**Comment by alesanchezr** [comment]
reasigned to main issue repo for implementation
