### ISSUE TITLE
Allow adding an "author" property to the lessons, how-to or errors

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#75]
We would like to encourage more collaboration to the breathecode content, for that reason we decided to add an "author" property to each article that will show the github username of the author and a github card `when username is hovered or clicked with the mouse`. [This is an example](https://lab.lepture.com/github-cards/#alesanchezr|medium) of a github card we could add `on hover`:

![screen shot 2019-02-18 at 4 30 20 pm](https://user-images.githubusercontent.com/426452/52977233-845a4780-339a-11e9-8134-69e641e1741d.png)

The author has to be specified on the front-matter of the article like all the other metadata its being specified right now.

Here are the templates being used to render the articles right now:
https://github.com/breatheco-de/content/tree/master/src/templates

To finish this feature you would have to update the `<Cover>` component (made in react) and also make sure to include the new `author` attribute in the graphql query for each template, for example here is the query for the lesson.js template:
https://github.com/breatheco-de/content/blob/master/src/templates/lesson.js#L44

**Comment by plucodev** [comment]
Starting working on this!
