### ISSUE TITLE
Lesson what is the internet is all wrong

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#76]
The original lesson was this one:
https://breatheco.de/en/lesson/internet-architecture/

Apparently the Dillinger app replaced the text with some jibberish.

**Comment by Camilocoo** [comment]
Ok I will fix it

**Comment by Camilocoo** [comment]
Ok, I will fix it @alesanchezr

**Comment by alesanchezr** [comment]
Ya terminaste esto? Porque lo cerraste?

**Comment by Camilocoo** [comment]
Si ya esta lista  http://docs.content.breatheco.de/lesson/what-is-the-internet/ @alesanchezr

**Comment by alesanchezr** [comment]
Excelente.
