### ISSUE TITLE
Finish BreatheCodes's Front-End Development 

### ISSUE THREAD

**Issue by Camilocoo** [breatheco-de/content#80]

**Comment by alesanchezr** [comment]
Excelente man, ahora que ya tienes mas conocimientos me gustaria que migraras el desarrollo que hiciste en breathecode a react.js, puedes usar este boilerplate como base: 
https://github.com/4GeeksAcademy/react-hello-webapp

**Comment by alesanchezr** [comment]
@Camilocoo

**Comment by Camilocoo** [comment]
Listo dale perfecto cuenta con eso @alesanchezr

**Comment by alesanchezr** [comment]
Parsero, porq
