### ISSUE TITLE
Node.js script to report how many articles are missing translation

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#84]
The following script is creating a json file with all the lessons in the platform:
https://github.com/breatheco-de/content/blob/master/generate-json.js

This is a sample of the json file being generated:
https://content.breatheco.de/static/api/lessons.json
```json
[
      {
            "slug": "[draft]mentoring-guidelines",
            "status": "draft",
            "title": "Mentor Guidelines",
            "date": "2017-09-24",
            "tags": [
                  "fale"
            ]
      },
      ...
]
```

We need to update that script to also include on the lesson object if the lesson is missing translation to Spanish or not.

Every lesson is supposed to have a spanish version with the same file name but ending on `.es.md` instead of just `.md`

For example, the lesson `learn-html.md` should have a `learn-html.es.md` alternative.

**Comment by rishabhkohli** [comment]
Can I work on this?

**Comment by alesanchezr** [comment]
I think the best approach will be having a `translations` array on the object that contains all the languages that have been found for that same lesson but in another language.

I'm also realizing now that it would be nice to have a `lang` property as well that specifies the language for the object.

```
[  
   {  
      "slug":"[draft]mentoring-guidelines",
      "status":"draft",
      "title":"Mentor Guidelines",
      "date":"2017-09-24",
      "tags":[  
         "fale"
      ],
      translations: ['en', 'fr']
   },
   {  
      "slug":"mentoring-guidelines.es",
      "status":"published",
      "title":"Pautas para el Mentor",
      "date":"2017-09-24",
      "tags":[  
         "fale"
      ],
      translations: ['es','fr']
   }
]
```

**Comment by rishabhkohli** [comment]
In that case, wouldn't it be better for English files to also have 'en' for the sake of clarity?

**Comment by alesanchezr** [comment]
English is the default that is why they don't have it, but you can create markdown files with the `.en.md` and it will still work.

Basically, if the files have a `.en.md` or if it does not have language, it means its English.

**Comment by nik72619c** [comment]
Is the issue free to work on? @alesanchezr

**Comment by rishabhkohli** [comment]
I have created a pull request to address this.

**Comment by alesanchezr** [comment]
ok I review check today, thanks @rishabhkohli 😄

**Comment by rishabhkohli** [comment]
Okay.
Let me know if any changes are required.
