### ISSUE TITLE
Integrar el nuevo home en el codigo actual de BreatheCode

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/content#87]
Ahora que ya tienes listo el home, porque no lo integras con el codigo de este repositorio?

Esta montado sobre Gatsby.js

**Comment by alesanchezr** [comment]
@Camilocoo

**Comment by Camilocoo** [comment]
Y como seria ahi ? Lo convierto todo a gatsby y despues lo anexo a donde ? @alesanchezr
